76 rewrite beambreak subsystem
midtownrobotics/2024-Offseason pull request #102
Opened 2024-10-24 01:22 UTC by darknessraider

2024-10-24 01:38 UTC, darknessraider commented
I was a little confused what Ankit was talking about with the IO protection or something? Hopefully I named the override class in a way that makes sense.

2024-10-26 23:48 UTC, Mysterium422 requested changes
- RobotContainer controls were changed to change RobotState. They should only change subsystem states.
- setRumble in the controller does not work since it only makes sure that a rumble wasn't set last cycle. Instead, it should be storing the most recently set rumble, and comparing that to the newly set rumble.

2024-10-27 00:13 UTC, Mysterium422 requested changes
The currentRumbleValue is only being updated when currentRumbleValue equals value. It needs to be the opposite

^ Im blind its being done correctly

2024-10-27 00:19 UTC, Mysterium422 approved these changes

2024-10-28 22:11 UTC, merged